name: Upgrade Version
on: push
  #push:
  #  tags:
  #    - '*'
jobs:
  replicate-file:  
    runs-on: ubuntu-latest
    name: Replicate File 
    steps:
    #- name: Checkout Project A
    #  uses: actions/checkout@v2
    #  with:
    #    path: ./projectA 
    - name: Checkout Project B
      uses: actions/checkout@master
      with: 
        repository: thecem/hassio-addon
        token: ${{ secrets.GH_TOKEN }}
        path: ./projectB 
    - name: Copy/Create file
      #run: |
      #  FILE=./projectA/file
      #  if [ -f "$FILE" ]; then
      #    echo "Copying $FILE"
      #    cp -R ./projectA/file ./projectB
      #  else 
      #    echo "Creating $FILE"
      #    touch ./projectB/file
      #  fi
      #             ./projectB/file sed -e s#0.0.0#$RELEASE_VERSION#  
      #run: |
      #  export RELEASE_VERSION=$(echo ${{ github.ref }} | sed -e s#refs/tags/v##) 
      #  echo "$RELEASE_VERSION"
      #  sed -e s#0.0.0#$RELEASE_VERSION# ./projectA/packaging/hassio/config.json > ./projectB/evcc/config.json
        # export SRC='"version"'
        # echo "$SRC"
        # export DST='  "version": "'$RELEASE_VERSION'"'
        # echo "$DST"
        #export RELEASE_VERSION=$(echo ${{ github.ref }} | sed -e s#refs/tags/v##)
        #echo "$RELEASE_VERSION"
        #echo $(date +'%Y-%m-%dT%H:%M:%S')
       # sed -i -e s#.*version.*#'  "version": "'$(echo ${{ github.ref }} | sed -e s#refs/tags/v##)'-'$(date +'%Y%m%d%H%M%S')'",'# ./projectB/evcc/config.json
       # sed -i -e s/\"version\":.*/\1 \"$(echo ${{ github.ref }} | sed -e s#refs/tags/v##)\"\,/ ./projectB/evcc/config.json
       # export RELEASE_VERSION=$(echo ${{ github.ref }} | sed -e s#refs/tags/v##)
       # sed -i -e s#.*version.*#'  "version": "'$RELEASE_VERSION'",'# ./projectB/evcc/config.json
       # sed -i -e s#\"version.*#'"version": "nightly-'$(date +'%Y%m%d%H%M%S')'",'# ./projectB/evcc-nightly/config.json
        #sed -i -e s#\"version.*#'"version": "'$(echo ${{ github.ref }} | sed -e s#refs/tags/##)'",'# ./projectB/evcc/config.json
      run: |
        sed -i -e s#\"version.*#\"version\":\ \"nightly-$(date +'%Y%m%d%H%M%S')\",# ./projectB/evcc-nightly/config.json
        sed -i -e s#\"version.*#\"version\":\ "$(echo ${{ github.ref }} | sed -e s#refs/tags/##)\",# ./projectB/evcc/config.json
    - name: Push Project B
      run: |
        cd ./projectB
        git add .
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -am "File Replicated from Project A"
        git push 
