name: Upgrade Version
on:
  push:
    tags:
      - '*'

jobs:
  upgrade-version-config-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pocket-apps/action-update-version@v1
        with:
          files: 'hassio-addon/hassio.addon.config.json'
          version-regexp: '\d+.\d+.\d+'
          branch-name: main
          author-name: thecem
      - uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          src_path: hassio-addon/hassio.addon.config.json
          dst_path: /evcc/config.json
          dst_owner: thecem
          src_branch: main
          dst_branch: main
          dst_repo_name: hassio-addon
