name: Upgrade Version
on:
  push:
    tags:
      - '*'

jobs:
  upgrade-version-config-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pocket-apps/action-update-version@v1
        with:
          files: 'config.json'
          version-regexp: '\d+.\d+.\d+'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'config.json'
          destination_repo: 'thecem/hassio-addon'
          destination_folder: 'evcc'
          user_email: 'example@email.com'
          user_name: 'dmnemec'
          commit_message: 'A custom message for the commit'
      - name: Deploy to docs repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./hassio-addon
          external_repository: thecem/hassio-addon
          publish_branch: main
          destination_dir: evcc
          allow_empty_commit: false
          commit_message: version update of config.json
  
