name: Upgrade Version
on:
  push:
    tags:
      - '*'

jobs:
  upgrade-version-config-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pocket-apps/action-update-version@v1
        with:
          files: 'thecem/evcc/config.json'
          version-regexp: '\d+.\d+.\d+'
          branch-name: 
