name: Upgrade Version
on:
  push:
    tags:
      - '*'

jobs:
  upgrade-version-config-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pocket-apps/action-update-version@v1
        with:
          files: 'hassio-addon/config.json'
          version-regexp: '\d+.\d+.\d+'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          source_file: 'config.json'
          destination_repo: 'thecem/hassio-addon'
          destination_folder: 'evcc'
          user_email: 'example@email.com'
          user_name: 'dmnemec'
          commit_message: 'A custom message for the commit'
      - name: Duplicate Release With Asset to public_Repo
        id: Release-AIO
        uses: Hs1r1us/Release-AIO@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # You need a new token to access the target Repository
        with:
          tag_name: 'inherit' # Must use 'inherit' to get the latest release
          body: 'hello world' # Will be added in the new release
          repo: 'thecem/hassio-addon' # The format is like owner/repo
          asset_files: './asset_file' # Will be added in the new release
