name: Upgrade Version
on:
  push:
    tags:
      - '*'

jobs:
  upgrade-version-config-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- uses: pocket-apps/action-update-version@v1
      #  with:
      #    files: 'hassio-addon/hassio.addon.config.json'
      #    version-regexp: '\d+.\d+.\d+'
      #    branch-name: main
      #    author-name: thecem
      
      - name: Update version
        # uses: pocket-apps/action-update-version@v1
        # with:
        #   files: "packaging/hassio/config.json"
        #   version-regexp: '\d+.\d+.\d+'
        #   branch-name: master
        #   author-name: evcc-io
        run: |
          sed -i -e s#0.0.0#$(echo ${{ env.GITHUB_REF }} | sed -e s#refs/tags/##)# packaging/hassio/config.json
          
      - uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          src_path: packaging/hassio/config.json
          dst_path: /evcc/config.json
          dst_owner: thecem
          src_branch: main
          dst_branch: main
          dst_repo_name: hassio-addon
